import { logger } from "../helpers/logger";

export interface TradeAIContextInput {
  assetSymbol: string;
  currentPrice: number;
  strikePrice: number;
  isUp: boolean;
  minutesToExpiry: number;
  impliedProb: number;
  positionType: "binary" | "range";
  lowerStrike?: number | null;
  upperStrike?: number | null;
}

/**
 * Generate a dynamic 15-word sentiment context using DeepSeek AI or a smart fallback.
 * Defaults to deepseek-v4-flash for low-latency responses.
 * Set DEEPSEEK_MODEL=deepseek-v4-pro in env to use the Pro model instead.
 */
export async function generateTradeAIContext(
  input: TradeAIContextInput,
): Promise<string> {
  const apiKey = process.env.DEEPSEEK_API_KEY;

  // 1. Generate Smart Fallback Template
  const buildFallback = () => {
    if (input.positionType === "range") {
      const lower = input.lowerStrike ?? input.strikePrice;
      const priceDiffPct = ((input.currentPrice - lower) / lower) * 100;
      return `${input.assetSymbol} is ${Math.abs(priceDiffPct).toFixed(1)}% ${priceDiffPct > 0 ? "above" : "below"} lower bound. ${(input.impliedProb * 100).toFixed(1)}% implied probability of settling inside range.`;
    } else {
      const priceDiffPct =
        ((input.currentPrice - input.strikePrice) / input.strikePrice) * 100;
      return `${input.assetSymbol} is ${Math.abs(priceDiffPct).toFixed(1)}% ${priceDiffPct > 0 ? "above" : "below"} strike. ${(input.impliedProb * 100).toFixed(1)}% implied probability of closing ${input.isUp ? "above" : "below"}.`;
    }
  };

  if (!apiKey) {
    logger.debug(
      "No DEEPSEEK_API_KEY provided, utilizing dynamic template fallback.",
    );
    return buildFallback();
  }

  // 2. Query DeepSeek AI
  const model = process.env.DEEPSEEK_MODEL ?? "deepseek-v4-flash";

  try {
    let tradeDetailsPrompt = "";
    if (input.positionType === "range") {
      const lower = input.lowerStrike ?? input.strikePrice;
      const upper = input.upperStrike ?? input.strikePrice;
      tradeDetailsPrompt = `Asset: ${input.assetSymbol}, Spot Price: $${input.currentPrice}, Range: $${lower} to $${upper}, Expiry: ${input.minutesToExpiry}m, Implied Probability: ${(input.impliedProb * 100).toFixed(1)}%.`;
    } else {
      tradeDetailsPrompt = `Asset: ${input.assetSymbol}, Spot Price: $${input.currentPrice}, Strike: $${input.strikePrice}, Target Direction: ${input.isUp ? "Above/Call" : "Below/Put"}, Expiry: ${input.minutesToExpiry}m, Implied Probability: ${(input.impliedProb * 100).toFixed(1)}%.`;
    }

    const systemInstructions =
      "You are a professional financial analyst and options strategist. " +
      "Summarize the trade's technical outlook or option sentiment in exactly or less than 15 words. " +
      "Be concise, extremely insightful, and avoid introductory words, pleasantries, or quotes.";

    const response = await fetch("https://api.deepseek.com/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        max_tokens: 60,
        messages: [
          { role: "system", content: systemInstructions },
          {
            role: "user",
            content: `Analyze this option contract and generate the summary: ${tradeDetailsPrompt}`,
          },
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      logger.error(
        { status: response.status, errorText, model },
        "DeepSeek API request failed",
      );
      return buildFallback();
    }

    const responseData = (await response.json()) as any;
    const aiText = responseData.choices?.[0]?.message?.content?.trim();

    if (aiText) {
      // Scrub any surrounding quotes just in case
      const cleaned = aiText.replace(/^["']|["']$/g, "").trim();
      logger.info(
        { cleaned, model },
        "AI trading context successfully generated by DeepSeek",
      );
      return cleaned;
    }

    return buildFallback();
  } catch (error) {
    logger.error(
      { error, model },
      "Error while generating AI context from DeepSeek",
    );
    return buildFallback();
  }
}
